# Generated by Django 5.0.7 on 2024-08-05 20:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.institution')),
            ],
            options={
                'db_table': 'tb_provider',
                'ordering': ['-created_date'],
            },
        ),
    ]
