# Generated by Django 5.0.7 on 2024-08-05 20:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_type_institution',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_api.county')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.typeinstitution')),
            ],
            options={
                'db_table': 'tb_institution',
                'ordering': ['-created_date'],
            },
        ),
    ]
