# Generated by Django 5.0.7 on 2024-08-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 13, 59, 35, 986504, tzinfo=datetime.timezone.utc)),
        ),
    ]
